language: scala
jdk: oraclejdk8
scala:
  - 2.11.8
  - 2.12.0
env:
  - PROTO=2.6.1
  - PROTO=3.0.2
  - PROTO=3.1.0

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dprotobuf.version=$PROTO clean coverage test coverageReport

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - neville.lyh@gmail.com
